### PR TITLE
waitUntil and addShMockCallback to reroute script commands to callback

### PR DESCRIPTION
**Pull request by keijohyttinen**
waitUntil mock and addShMockCallback

sh mock can be extended with callback for sh commands that contains a keyword.
This opens up more chances to implement something specific for some commands, e.g. just reroute some app/tool commands for further handling, logging, mocking, verification etc.

### CODE REVIEW

**Comment by nre-ableton** [comment]
Thanks for your PR! I haven't gone through the code line-by-line yet, but I have some general questions about your PR.

Regarding the `waitUntil` mock, your implementation has a different signature than the Jenkins pipeline step. The Jenkins step doesn't take any arguments, and it also behaves differently than the mock. According to the documentation:

>  Runs its body repeatedly until it returns true. If it returns false, waits a while and tries again. (Subsequent failures will slow down the delay between attempts.) There is no limit to the number of retries, but if the body throws an error that is thrown up immediately.

I can see the default Jenkins behavior doesn't make sense when running unit tests -- we don't want to add exponential backoff, and retrying forever is probably a bad idea as well. But providing an override which takes an `int` means that you could write code in a production pipeline which would pass the unit tests and yet fail on a real Jenkins instance:

```groovy
waitUntil(5) {
  true
}
```

I tried the above code in a Jenkins sandbox and got the following exception: `java.lang.IllegalArgumentException: Expected named arguments but got 5`. I think that we should remove the override and just hardcode in a limit of 100 retries. We can document that the method behaves a bit differently than the real Jenkins pipeline step.

As for `addShMockCallback`, I think I see the intention here and I like it -- is the idea to be able to run a closure when the `sh` mock is found, instead of just a static string/return code as the framework does now?

I need to think about this commit a bit, but my initial reaction is that this could be implemented in a slightly simpler way. We could modify `MockScriptOutput` to also hold a `Closure` object for the callback. I would like for the matching behavior to be consistent, and also determined by the user. In other words, I like your idea to use `script.contains` for the match, but I don't like that this is only applied for closures and not also static data.

I will create a branch based on your PR and do some thought experiments, and will post back in this PR when I have something to show.

**Comment by keijohyttinen** [comment]
I'm OK with hard coded limit of 100 loops. I was just thinking of giving that option but seems like it's not needed and might also confuse the users. And what's more important you pinpointed how it could cause troubles with production pipelines.

> -- is the idea to be able to run a closure when the sh mock is found, instead of just a static string/return code as the framework does now

Yes, that's the idea. I did it quickly for specific use case and need of our pipeline implementation to trigger actions which were indirectly done by some scripts -> can have better control of tests. 

Good call also with `MockScriptOutput` to hold both options. If will be useful to have `scripts.contains` match option for static data as well.

Downside of the current implementation of `addShMockCallback` is that it's user's responsibility to make implementation for returnStdout and returnStatus. I was thinking of how to avoid that and were preparing similar thing with your idea to combine implementation of callback and static data.  E.g. user needs to provide returnStdout and returnStatus in `addShMockCallback`.

**Comment by nre-ableton** [comment]
@keijohyttinen Ok, I've pushed a branch called `nre/master/callbackmock` based on yours which contains two fixups, one for each of your commits. It's not yet 100% complete but please take a look.

In general, I cleaned up the code formatting to match our standards, which isn't publicly documented yet, so you would have no way of knowing what these are other than by guessing based on the surrounding code. Sorry about that, we will publish contributing guidelines soon. :wink: I also reordered the methods so that they are alphabetical.

The first fixup is https://github.com/AbletonDevTools/jenkins-pipeline-mocks/commit/d0d87c682fa7021d380784af42da5396aa94c5fb and is for the `waitUntil` mock. Since we seem to be in agreement on the changes here, this will probably look like as you might expect. The `waitUntilExceedSetLimit` test is also not necessary anymore so it was removed.

The second fixup (https://github.com/AbletonDevTools/jenkins-pipeline-mocks/commit/9572682ddbc7f9ded0e07b6a99baf03228e2bb79) is a bit bigger, and doesn't address all of the work you did in your original commit. It does add a `Closure` field to the `MockScriptOutput` class as we discussed. I changed the way that the callback is expected to behave, though. Now it is only passed the `script` string... I don't think that the mock needs to be aware of the `returnStdout` or `returnStatus` values. The callback is expected to return a `Map` with `stdout` and `exitValue`, which is handled with the same codeflow as was used before. I added a few more tests to make sure that everything behaves properly, and they should all be passing.

The one thing that's missing is the flexible matching of the `script` string. I'm not entirely sure how to do this best and need to think about it a bit more. I'm thinking we might add another parameter to both `addShMock` overrides, so we end up with something like this:

```groovy
static Map<String, Boolean> mockScriptMatchesExactly = [:]

// Same goes for the other addShMock override which takes a Closure
static void addShMock(String script, boolean matchExactly, String stdout, int exitValue) {
  mockScriptMatchesExactly[script] = matchExactly
  mockScriptOutputs[script] = new MockScriptOutput(null, stdout, exitValue)
}
```

Then in the `sh` mock implementation, we'd look at the value in the map and use that to find the script accordingly. This is pretty hacky, though. Another idea is to create another set of overrides which take a `Pattern` object, like so:

```groovy
static void addShMock(String script, String stdout, int exitValue) { ... }

static void addShMock(Pattern script, String stdout, int exitValue) { ... }

static void addShMock(Script string, Closure callback) { ... }

static void addShMock(Pattern script, Closure callback) { ... }
```

I'm not sure how I feel about this approach either. Anyways, like I said, I need some time to think about the matching a bit more. Would you be ok if we solve this problem in two parts, one PR for the `waitUntil` and callback closure, and another PR for the flexible matching?

**Comment by keijohyttinen** [comment]
Looks good to me. And I'm fine with another PR for flexible matching.

Your proposal looks good. Just suggestion: matchExactly could be also optional argument like:
`static void addShMock(String script, String stdout, int exitValue, boolean matchExactly=false)`

One more option could be to have just `addShMock(Map params)` or `addShMock(String script, Map params)`, which can be extended for new arguments in a flexible way. Then `matchExactly` can be optional key which defaults to true. Of course, this implementation requires validation of keys and combinations.

**Comment by nre-ableton** [comment]
@keijohyttinen in general, I'm a big fan of using `Map args` and then providing friendly overrides. You are correct regarding the extra error checking, but I don't mind this so long as we document everything.

Regarding the merge strategy for the 2 PRs, would you mind if I close this PR and open up two new ones? Our Jenkins instance has the `AbletonDevTools` GitHub organization hardcoded as the git origin, and thus can't build external pull requests (hence the "pending" status checks; the build actually failed but it won't report back).

Sorry about this -- we don't get many external pull requests to these pipeline projects, so it's a problem haven't managed to solve yet.

**Comment by nre-ableton** [comment]
Closing, since https://github.com/AbletonDevTools/jenkins-pipeline-mocks/pull/21 has been merged. Thanks again @keijohyttinen !

**Pull request closed without merging**
